"""empty message

Revision ID: 2882a865d498
Revises: 
Create Date: 2018-09-03 18:09:44.385669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2882a865d498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_foodtypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typeid', sa.String(length=200), nullable=True),
    sa.Column('typename', sa.String(length=200), nullable=True),
    sa.Column('childtypenames', sa.String(length=200), nullable=True),
    sa.Column('typesort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_foodtypes')
    # ### end Alembic commands ###
