"""empty message

Revision ID: ab94713e6be4
Revises: 2882a865d498
Create Date: 2018-09-03 19:09:56.735569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab94713e6be4'
down_revision = '2882a865d498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productid', sa.String(length=20), nullable=True),
    sa.Column('productimg', sa.String(length=200), nullable=True),
    sa.Column('productname', sa.String(length=200), nullable=True),
    sa.Column('productlongname', sa.String(length=200), nullable=True),
    sa.Column('isxf', sa.Integer(), nullable=True),
    sa.Column('pmdesc', sa.Integer(), nullable=True),
    sa.Column('specifics', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('marketprice', sa.Float(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('childcid', sa.Integer(), nullable=True),
    sa.Column('childcidname', sa.String(length=100), nullable=True),
    sa.Column('dealerid', sa.String(length=10), nullable=True),
    sa.Column('storenums', sa.Integer(), nullable=True),
    sa.Column('productnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('axf_goods')
    # ### end Alembic commands ###
